name: rust workflow
on:
  push:
  pull_request:
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  CARGO_TERM_COLOR: always
jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Execute Codes
      run: |
        for i in `ls -al .`; do if [[ -d $i ]] &&  [[ -f "$i/Cargo.toml" ]];then cd $i; cargo build --verbose; cargo test --verbose; cd ..; fi; done